### Key Bindings ###

# Reload Tmux Configuration
unbind r
bind r source-file ~/.tmux.conf

# Pane Navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

### Settings ###

# Clock
set-option -g clock-mode-style 12

# Mouse
set -g mouse off

### Tmux Plugin Manager ###

# List of Plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX Plugin Manager (must stay last in this file)
run '~/.tmux/plugins/tpm/tpm'
